### ISSUE TITLE
Error TestsetPreparation.py

### ISSUE THREAD

**Issue by Onotoko** [mariolew/Deep-Alignment-Network-tensorflow#17]
Hi,
I have an error when run TestsetPreparation.py file:
Traceback (most recent call last):
  File "TestSetPreparation.py", line 19, in <module>
    commonSet.PrepareData(commonSetImageDirs, commonSetBoundingBoxFiles, meanShape, 0, 1000, False)
  File "/home/diffdeep/Documents/train_dan/Deep-Alignment-Network-tensorflow-master-2/DAN-TF/ImageServer.py", line 60, in PrepareData
    boundingBoxDict = pickle.load(open(boundingBoxFiles[i], 'rb'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd3 in position 0: ordinal not in range(128)
Please suggest me some advice. Thanks

**Comment by duduOliver** [comment]
In `ImageServer.py`, turn `boundingBoxDict = pickle.load(open(boundingBoxFiles[i], 'rb'))` to `boundingBoxDict = pickle.load(open(boundingBoxFiles[i], 'rb'), encoding='bytes')`

**Comment by Onotoko** [comment]
Hi duduOliver,
Thank you very much :)

**Comment by 1700117HLT** [comment]
Hi,
I have an error when run TestsetPreparation.py file:
File "TestSetPreparation.py", line 20, in <module>
commonSet.PrepareData(commonSetImageDirs, commonSetBoundingBoxFiles, meanShape, 0, 1000, False)
    ImageServer.py", line 70, in PrepareData
boundingBoxes.append(boundingBoxDict[basename])
KeyError: 'image_0193.png'

**Comment by dapipi0315** [comment]
> ```
> Hi,
> ```
> 
> I have an error when run TestsetPreparation.py file:
> File "TestSetPreparation.py", line 20, in 
> commonSet.PrepareData(commonSetImageDirs, commonSetBoundingBoxFiles, meanShape, 0, 1000, False)
> ImageServer.py", line 70, in PrepareData
> boundingBoxes.append(boundingBoxDict[basename])
> KeyError: 'image_0193.png'

Excuse me. Have you solved the problem? I meet the same error with you. Thank you very much!

**Comment by niceweipeng** [comment]
> > ```
> > Hi,
> > ```
> > 
> > 
> > I have an error when run TestsetPreparation.py file:
> > File "TestSetPreparation.py", line 20, in
> > commonSet.PrepareData(commonSetImageDirs, commonSetBoundingBoxFiles, meanShape, 0, 1000, False)
> > ImageServer.py", line 70, in PrepareData
> > boundingBoxes.append(boundingBoxDict[basename])
> > KeyError: 'image_0193.png'
> 
> Excuse me. Have you solved the problem? I meet the same error with you. Thank you very much!

change the dict key to str ,like this :

        boundingBoxDict = {}
        for i in range(len(imageDirs)):
            filenamesInDir = glob.glob(imageDirs[i] + "*.jpg")
            filenamesInDir += glob.glob(imageDirs[i] + "*.png")
            # import pdb; pdb.set_trace()
            if boundingBoxFiles is not None:
                boundingBoxDictTmp = pickle.load(open(boundingBoxFiles[i], 'rb'), encoding='bytes')
                for k,v in boundingBoxDictTmp.items():
                    str_tmp = str(k,encoding = "utf8")
                    boundingBoxDict[str_tmp] = v
