### ISSUE TITLE
error on trainingsetpreparation 

### ISSUE THREAD

**Issue by qmj123** [mariolew/Deep-Alignment-Network-tensorflow#27]
Hi,
When I run trainingsetpreparation .py,
Creating perturbations of 0 shapes
E:\anaconda\lib\site-packages\numpy\core\fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
E:\anaconda\lib\site-packages\numpy\core\_methods.py:80: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
E:\anaconda\lib\site-packages\numpy\core\_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
E:\anaconda\lib\site-packages\numpy\core\_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
E:\anaconda\lib\site-packages\numpy\core\_methods.py:127: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "TrainingSetPreparation.py", line 17, in <module>
    trainSet.NormalizeImages()#去均值，除以标准差
  File "F:\code\Deep-Alignment-Network-tensorflow-master\DAN-TF\ImageServer.py", line 219, in NormalizeImages
    plt.imshow(meanImg[:,:,0], cmap=plt.cm.gray)
IndexError: invalid index to scalar variable.
Can you  help me ?
Thank you !

**Comment by Louise163** [comment]
I ran into the same problem, have you solved the problem yet?

**Comment by Louise163** [comment]
Oh maybe you didn't download the datasets yet.
