### ISSUE TITLE
some issues about data set

### ISSUE THREAD

**Issue by Chromer163** [mariolew/Deep-Alignment-Network-tensorflow#5]
In TrainingSetPreparation.py, 
![image](https://user-images.githubusercontent.com/16739522/38077712-831ecbcc-336c-11e8-8ae2-95e05b24da7f.png)
I wonder whats the format of LFPW or HELEN and how to ensure that images corresponding to data?

**Comment by mariolew** [comment]
You can google and download 300-w dataset, and see the format.

There is a .pts file with the same name of the corresponding photo, the format of the .pts file can be found in the 300-w website.

**Comment by Chromer163** [comment]
thanks.
In the paper, it trained 2 models: DAN  and DAN-Menpo. For DAN, it uses only 3148 images, so  I wander 
is it enough for the training of CNN?
![image](https://user-images.githubusercontent.com/16739522/38128459-3bdbda4a-342d-11e8-8b75-a8d5530260fa.png)

**Comment by mariolew** [comment]
3000+ images are not enough to train the model, so DAN conduct several data augmentation techniques like random shift, rotate and mirror.

**Comment by Chromer163** [comment]
Ok, thanks. You are really kind.

**Comment by Chromer163** [comment]
`def GeneratePerturbations(self, nPerturbations, perturbations):`
Is this function used for data augmentation?
so how many images will be augmented per image?
I see in the code `trainSet.GeneratePerturbations(10, [0.2, 0.2, 20, 0.25])#`
Does it mean 10 per images?

**Comment by mariolew** [comment]
对的，请说中文，早该如此啦。

**Comment by Chromer163** [comment]
mobile net是另外加进去的吗？

**Comment by mariolew** [comment]
是的。

**Comment by Chromer163** [comment]
`        plt.savefig("../meanImg.jpg")`
``TypeError: integer argument expected, got float
这个是怎么回事呢，meanImg这个矩阵的元素是int，怎么还会报错？

**Comment by mariolew** [comment]
错误信息写的是got float，说明meanImg不是int呢，你再看看?

**Comment by Chromer163** [comment]
meanImg的每个元素都是int,我将`plt.savefig("../meanImg.jpg")`改为`plt.savefig("../meanImg.png")`后，就生成了
![image](https://user-images.githubusercontent.com/16739522/38467418-d1c46f38-3b6a-11e8-9807-7659311a72ce.png)
但是不知道为什么。
此外运行trainDAN.py会报这个错：
![image](https://user-images.githubusercontent.com/16739522/38467425-ee6a2362-3b6a-11e8-9d2d-0cc71601803a.png)

**Comment by mariolew** [comment]
很显然，你处理数据得到的npz不叫这个名字，你得去看看你的叫什么名字，nimgs=40xxx，这个40是因数据数量而异的。

**Comment by Chromer163** [comment]
最近想训练这个模型，关于如何运行，是不是先分别run `training\testSetPreparation.py`这两个文件，生成所需要的.npz然后再去run `trainDAN.py`？
我在运行`testSetPreparation.py`时，抛出一个error:
`Traceback (most recent call last):
  File "/home/huangyangguang/PycharmProjects/Deep-Alignment-Network-tensorflow-master/DAN-TF/TestSetPreparation.py", line 20, in <module>
    commonSet.PrepareData(commonSetImageDirs, commonSetBoundingBoxFiles, meanShape, 0, 1000, False)
  File "/home/huangyangguang/PycharmProjects/Deep-Alignment-Network-tensorflow-master/DAN-TF/ImageServer.py", line 60, in PrepareData
    boundingBoxDict = pickle.load(open(boundingBoxFiles[i], 'rb'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd3 in position 0: ordinal not in range(128)`

**Comment by mariolew** [comment]
Emmm，你把`commonSetBoundingBoxFiles = ["../data/boxesLFPWTest.pkl", "../data/boxesHelenTest.pkl"]`里面对应的pkl改成`py3`开头的文件即可，我忘了改上去了，不好意思，具体你可以看看data文件夹里`py3`开头的文件名。

**Comment by Chromer163** [comment]
嗯嗯，那这两个也需要改吗？
`challengingSetImageDirs = ["../data/images/ibug/"]
challengingSetBoundingBoxFiles = ["../data/boxesIBUG.pkl"]

w300SetImageDirs = ["../data/images/300W/01_Indoor/", "../data/images/300W/02_Outdoor/"]
w300SetBoundingBoxFiles = ["../data/boxes300WIndoor.pkl", "../data/boxes300WOutdoor.pkl"]`

**Comment by mariolew** [comment]
都改的。

**Comment by Chromer163** [comment]
嗯嗯，按照你说的以后，我得到了以下文件：
![image](https://user-images.githubusercontent.com/16739522/38476156-d6539136-3bde-11e8-8bde-cedabe4c5133.png)
现在的问题是，这四个文件是test和train各两个吗？
具体是怎么使用呢？
比如trainDAN里面：
![image](https://user-images.githubusercontent.com/16739522/38476204-1435e454-3bdf-11e8-9d25-69e978078abe.png)

**Comment by mariolew** [comment]
这个就随你咯，看你需求吧。都行。

**Comment by Chromer163** [comment]
恩，我的理解
![image](https://user-images.githubusercontent.com/16739522/38478020-b438079e-3be8-11e8-86b1-b7100e5fcd9e.png)这三个.npz文件用做验证集，然后剩下的那个作为训练集？
现在的问题是感觉我生成的
![image](https://user-images.githubusercontent.com/16739522/38478072-fac65cf6-3be8-11e8-9382-93172f5f2246.png)这个训练集里面怎么只有100个数据。。。
那个 `trainSet.GeneratePerturbations(10, [0.2, 0.2, 20, 0.25])#位移0.2，旋转20度，放缩+-0.25`这句是用来数据扩充的吗？那么该如何使用呢？这个训练集的数据量肯定是不对的。

**Comment by mariolew** [comment]
trainset的生成代码里面有一些数字你可以修改一下，这样就不会是100了。

**Comment by mariolew** [comment]
这个错误太奇怪了，我的mac上是不会出这种错误的，看它字面意思应该是开辟空间出错？

**Comment by Chromer163** [comment]
有没有可能是tensorflow版本不对？我看你使用的是1.5.0,我下载了r1.5但是我刚才看了一下居然是
![image](https://user-images.githubusercontent.com/16739522/38498709-e50ed100-3c37-11e8-9838-4ac02ad449e2.png)
![image](https://user-images.githubusercontent.com/16739522/38498825-39098bba-3c38-11e8-8412-00c55fe6a407.png)
不知道如何找到你说的1.5.0

**Comment by mariolew** [comment]
这个不好说，要装1.5直接pip install tensorflow==1.5.0即可

**Comment by Chromer163** [comment]
似乎跟validation set有关，在trainDAN.py里面，送入validation set的.npz文件不能太大，我试了一下，有四个.npz文件，其中大小5～7M的都可以train，但是几十M的就会报这个错误。
(我目前没有使用GPU，等明天换到服务器上试试)
另外我有个问题想咨询一下：我现在电脑上有不同的tensorflow的GPU版本，但是要用你的1.5.0gpu版本的tensorflow，在不卸载之后版本的tensorflow情况下，如何操作？
就是担心1.5.0的cuda和cudnn和我之前的不一样。

**Comment by mariolew** [comment]
cuda和cudnn可以装多个的，具体请搜索。

**Comment by mariolew** [comment]
@Chromer163 跟validationset有关的话，可能是因为数据经模型前传占内存过大，你可以每次测试的时候少一些数据，因为虽然数据几十兆，但是经过网络以后就很大了。

**Comment by hengshanji** [comment]
Hi, 我将TrainingSetPreparation.py:13  修改为trainSet.PrepareData(imageDirs, None, meanShape, 100, 100000, True)  生成的训练数据有60960个和DeepAlignmentNetwork原始项目的训练集大小一样，gtx 1080下一次迭代5分钟，我改了batchsize=64。 想咨询一下Landmark68Test函数你没有实现对吧？ 这个是zjjMaiMai实现的版本里的吧。 有什么可视化结果的代码吗？

**Comment by mariolew** [comment]
@hengshanji 可视化结果就run出landmark的值来，然后画出来即可，绘图的代码与tensorflow没有关系，你用原作者的代码绘图也可以的。

**Comment by THtanghuan** [comment]
请问一下，为什么testDAN.py运行出的每张图片的误差结果都是同一个结果啊？是什么意思呢

**Comment by mariolew** [comment]
具体问题能截图或者log发一下吗，因为我一直没有机器训练，事实上我还没有试过test，目前训练肯定没问题，测试代码我再看看?

**Comment by THtanghuan** [comment]
不好意思啊，我不会讲图片放进来，能不能加个微信交流一下啊，th284299917，谢谢

**Comment by Chromer163** [comment]
给你看一下testDAN.py的测试结果，我也是一个值。

**Comment by Chromer163** [comment]
我有一个疑问，就是训练部分使用的是LFPW HELEN AFW这三个，而测试部分使用的challenging set 是跟Ibug有关，而Ibug没有参与训练，怎么保证模型在这个数据集上面的表现呢？

**Comment by niceworld** [comment]
你好，不知道tesetDAN.py 错误率一样的问题找到了么？代码看起来没什么问题

**Comment by mariolew** [comment]
@niceworld 就不要循环就好啦。或者，每次循环的时候就对一张图操作即可。

**Comment by niceworld** [comment]
@mariolew 感谢你的回复...我现在改成这样就不会出现结果一样的情况了.
```
for iter in range(100):
        RandomIdx = np.random.choice(Xtest.shape[0],1,False)
        TestErr= sess.run(dan['S2_Cost'],{dan['InputImage']:Xtest[RandomIdx],dan['GroundTruth']:Ytest[RandomIdx]
....
```
但是又有新的问题，这是训练的
![image](https://user-images.githubusercontent.com/5638159/39037871-663db8f2-44b4-11e8-8a49-21a27ba97228.png)
这是测试时候的..差距有点大啊...
![image](https://user-images.githubusercontent.com/5638159/39037900-8091fb8c-44b4-11e8-812f-0ed47c137850.png)

**Comment by mariolew** [comment]
@niceworld 测试需要normalize，代码忘了写了

**Comment by mariolew** [comment]
你知道裁取人脸的框的位置和大小就可以算出来。

**Comment by niceworld** [comment]
@mariolew 这就是问题的关键了...代码中，测试的图片是直接通过给出的gt截取的，如果是要用自己的数据测试，那不是还要接要给人脸检测器？

**Comment by mariolew** [comment]
当然要啊，这只是特征点定位算法，没有包括人脸检测。

**Comment by BKZero** [comment]
you all are funny, guys……what will the international friends do if you all speak Chinese[Emoji humor]

**Comment by mariolew** [comment]
Just join the talk, haha.

**Comment by NanKeRen2020** [comment]
您好，mariolew，请问能分享一下预测部分的代码吗？如果可以的话，麻烦请发邮箱shengqiang8814@qq.com，thx very much！

**Comment by lanshanikilven** [comment]
@mariolew  您好，能分享一下预测部分的代码吗？如果可以的话，麻烦发到targetinsight@163.com，谢谢！

**Comment by xiaomingdaren123** [comment]
@mariolew  想问您几个问题
1、我训练的时候到最后为什么testERR和batchErr变成了NAN，难道是学习速率太大了吗，我的学习速率没有改，还是0.001？
2、就是在CropResizeRotate预处理数据的阶段，不太理解destShape是干嘛的，为啥要求出initshape到destshape的变换，最终得到的initLandmarks就是网络阶段的S0，不太理解S0为什么这么求？
3、对tensorflow不太熟悉，目前想改这个网络，但是遇到了一点问题，想将网络中卷积网络的输出放到自定义的函数中进行处理在放入网络中，但是自定义的函数输入是numpy类型，后面还有赋值操作。但是网络传出的tensor 类型，我尝试过一些方法将numpy转tensor，但是tensor又不好进行赋值改值的操作，请问您在tensorflow中有没有什么比较好的方法？
谢谢您！

**Comment by githubcyy** [comment]
@xiaomingdaren123 请问NAN的问题解决了吗，我也遇到了同样的问题

**Comment by githubcyy** [comment]
> @niceworld 测试需要normalize，代码忘了写了

请问测试的时候怎样normalize呢

**Comment by niceworld** [comment]
> > @niceworld 测试需要normalize，代码忘了写了
> 
> 请问测试的时候怎样normalize呢

就按照TrainingSetPreparation.py中的做就好了 ImageServer.NormalizeImages()

**Comment by maidanglao990** [comment]
> @mariolew 想问您几个问题
> 1、我训练的时候到最后为什么testERR和batchErr变成了NAN，难道是学习速率太大了吗，我的学习速率没有改，还是0.001？
> 2、就是在CropResizeRotate预处理数据的阶段，不太理解destShape是干嘛的，为啥要求出initshape到destshape的变换，最终得到的initLandmarks就是网络阶段的S0，不太理解S0为什么这么求？
> 3、对tensorflow不太熟悉，目前想改这个网络，但是遇到了一点问题，想将网络中卷积网络的输出放到自定义的函数中进行处理在放入网络中，但是自定义的函数输入是numpy类型，后面还有赋值操作。但是网络传出的tensor 类型，我尝试过一些方法将numpy转tensor，但是tensor又不好进行赋值改值的操作，请问您在tensorflow中有没有什么比较好的方法？
> 谢谢您！

后来解决这个Nan的问题了吗？我也遇到了

**Comment by Brystone** [comment]
嗨，当我运行trainDAN的时候，在第44行代码 `nSamples = trainSet.gtLandmarks.shape[0]` 时，
报了一个错：`AttributeError: 'tuple' object has no attribute 'gtLandmarks'`，
请问这个错误该怎么解决呢？

**Comment by BlinkingStalker** [comment]
我的显卡是2070，超过1000的图片训练集就跑不了了？请问楼主如果我分成多个300张图的小训练集，一个一个跑，结果会受影响吗？
